# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MilestoneSerializer`.
# Please instead update this file by running `bin/tapioca dsl MilestoneSerializer`.


class MilestoneSerializer
  sig { returns(Milestone) }
  def milestone; end
end
