# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `QuestSerializer`.
# Please instead update this file by running `bin/tapioca dsl QuestSerializer`.


class QuestSerializer
  sig { returns(Quest) }
  def quest; end
end
